### ISSUE TITLE
Card seems hard coded for 100 characters max

### ISSUE THREAD

**Issue by tomlut** [faeibson/lovelace-multiline-text-input-card#12]
![Screenshot 2024-10-07 at 11-04-34 Administration – Home Assistant](https://github.com/user-attachments/assets/cee60595-2d5d-4aae-bba5-c98dbaa70427)

```
type: custom:lovelace-multiline-text-input-card
autosave: false
entity: input_text.ignore_list
max_length: 255
min_length: 0
show_success_messages: true
title: Ignore List
buttons:
  clear: 1
  paste: 2
  save: true
```

With this configuration I can not exceed 100 characters.

**Comment by ildar170975** [comment]
A default max length for an `input_text` entity is 100 chars.
You need to define a max length for the entity itself.
![image](https://github.com/user-attachments/assets/fcaa73b0-0112-4882-8868-24cfc6d7f7b7)
```
type: entities
entities:
  - type: custom:lovelace-multiline-text-input-card
    entity: input_text.test_text_255
    max_length: 255
```
```
input_text:
  test_text_255:
    max: 255
```
