### ISSUE TITLE
Buttons are not centered

### ISSUE THREAD

**Issue by ildar170975** [faeibson/lovelace-multiline-text-input-card#13]
Consider this code:
```
type: entities
entities:
  - type: custom:lovelace-multiline-text-input-card
    entity: input_text.test_text_255
```
Buttons are not centered: 
![image](https://github.com/user-attachments/assets/9a836e2a-148b-4de1-8b0e-794abc3e33d3)

Seems that the 2nd span element prevents it:
![image](https://github.com/user-attachments/assets/c7358f3c-5ad9-45dc-b3e6-05d66eab1d53)

Fixed it by adding `margin-top: 6px;` for a `flex` element:
![image](https://github.com/user-attachments/assets/e77555d1-fd47-4495-9aee-dda7de7a1d8b)

But a proper value may depend on a particular client.
