### ISSUE TITLE
Horizontal resizing of textarea may cause glitches

### ISSUE THREAD

**Issue by ildar170975** [faeibson/lovelace-multiline-text-input-card#14]
Consider a card:
```
type: entities
entities:
  - type: custom:lovelace-multiline-text-input-card
    entity: input_text.test_text_255
```
Default look:
![image](https://github.com/user-attachments/assets/a89bad2f-4494-46f4-a22e-a1e9db0114f2)

Horizontal resizing causes glitches:
![image](https://github.com/user-attachments/assets/59465ef6-62e4-4969-b0ce-8514a26c4d35)

![image](https://github.com/user-attachments/assets/88708b7b-e5c4-4fdf-a219-c9311429625d)

May be fixed by
```
        .textarea {
          max-width: 100%;
          min-width: 100%;
        }
```
